services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs:ro
    depends_on:
      - deno
    restart: unless-stopped
    networks:
      - webnet

  deno:
    build:
      context: ./game-server/
      dockerfile: Dockerfile
    container_name: deno_server
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
